Repository HussnainAhmad1606/CodySnippets-Hacktoberfest-2023, pull requests merged in 2023-10, with the labels that each got.

#1 Complete Authentication backend, implement zustand and daisy UI
  package-lock.json
  package.json
  src/middlewares/connectDB.js
  src/models/User.js
  src/pages/api/auth/login.js
  src/pages/api/auth/signup.js
  src/store/store.js
  tailwind.config.js
Labels: good first issue, hacktoberfest-accepted

#2 store.js
  src/store/store.js
Labels: hacktoberfest-accepted

#3 HeroSection.js
  src/components/HeroSection.js
Labels: hacktoberfest-accepted

#4 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#5 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#9 Added Categories Section
  public/HTML.png
  src/app/categories/page.js
  src/components/Categories.js
  src/components/CategoryCard.js
Labels: enhancement, hacktoberfest-accepted

#10 Added CodeSnipet Section
  package-lock.json
  package.json
  src/app/trending/page.js
  src/components/Categories.js
  src/components/CategoryCard.js
  src/components/CodeSnippet.js
  src/components/SnippetContainer.js
Labels: enhancement, hacktoberfest-accepted

#8 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted

#12 Fix Redirect & Contact Form Issues
  src/app/contact/page.js
  src/components/Login.js
  src/components/Signup.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#14 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#15 Added hover effect on Login and Explore buttons
  src/components/HeroSection.js
  src/components/Navbar.js
  src/css/globals.css
Labels: enhancement, good first issue, hacktoberfest-accepted
